name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t dattasandeep/genesis-backend1:latest .
          docker push dattasandeep/genesis-backend1:latest
#name: CI/CD
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Login to Docker Hub
#        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and push Docker image
#        run: |
#          docker build -t dattasandeep/genesis-backend1:latest .
#          docker push dattasandeep/genesis-backend1:latest
#
#      - name: Deploy to Vercel
#        run: |
#          vercel --prod --token $VERCEL_TOKEN --confirm
#        env:
#          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
